# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-kr
  weight: 1
  contentDir: content/ko
  title: 강주현
  params:
    description: 전북대 컴퓨터공학부
  menu:
    main:
     - name: "홈"
       url: "/"
       weight: 10
     - name: "자기소개"
       url: "/about/"
       weight: 20
     - name: "프로젝트"
       url: "/project/"
       identifier: project
       weight: 30
     - name: "전체"
       url: "/project/"
       parent: project
       weight: 31
     - name: "보안"
       url: "/project/security/"
       parent: project
       weight: 32
       weight: 33
     - name: "웹/앱"
       url: "/project/java-set/"
       parent: project
       weight: 34
     - name: "인공지능 AI활용"
       url: "/project/ai-mlp/"
       parent: project
       weight: 35
     - name: "미래 계획"
       url: "/goals/"
       identifier: goals
       weight: 40
     - name: "로드맵"
       url: "/goals/#roadmap"
       parent: goals
       weight: 41
     - name: "자격증"
       url: "/goals/certs/"
       parent: goals
       weight: 42
     - name: "연락"
       url: "/contact/"
       weight: 50

en:
  languageCode: en-us
  weight: 2
  contentDir: content/en
  title: "kang Juhyeon"
  params:
    description: "Computer Science student at JBNU"
  menu:
    main:
      - name: "Home"
        url: "/en/"
        weight: 10
      - name: "About"
        url: "/en/about/"
        weight: 20
      - name: "Projects"
        url: "/en/project/"
        identifier: project
        weight: 30
      - name: "All"
        url: "/en/project/"
        parent: project
        weight: 31
      - name: "Security"
        url: "/en/project/security/"
        parent: project
        weight: 32
      - name: "Web/App"
        url: "/en/project/java-set/"
        parent: project
        weight: 34
      - name: "AI"
        url: "/en/project/ai-mlp/"
        parent: project
        weight: 35
      - name: "Future Plans"
        url: "/en/goals/"
        identifier: goals
        weight: 40
      - name: "Roadmap"
        url: "/en/goals/#roadmap"
        parent: goals
        weight: 41
      - name: "Certificates"
        url: "/en/goals/certs/"
        parent: goals
        weight: 42
      - name: "Contact"
        url: "/en/contact/"
        weight: 50

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
