# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-kr
  weight: 1
  contentDir: content/ko
  title: 강주현의 포트폴리오
  params:
    description: 전북대 컴퓨터공학부

en:
  languageCode: en-us
  weight: 2
  contentDir: content/en
  title: "Juhyeon Kang's portfolio"
  params:
    description: "Computer Science student at JBNU"
  menu:
    main:
      - name: Home
        url: /en/
        weight: 10
      - name: About
        url: /en/about/
        weight: 20
      - name: Projects
        url: /en/project/
        weight: 30

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
