# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
 - name: 홈
   url: /
   weight: 10
 - name: 자기소개
   url: /about/
   weight: 20
 - name: 프로젝트
   url: /project/
   identifier: project
   weight: 30
 - name: 전체
   url: /project/
   parent: project
   weight: 31
 - name: 보안
   url: /project/security/
   parent: project
   weight: 32
 - name: 웹/앱
   url: /project/java-set/
   parent: project
   weight: 34
 - name: 인공지능 AI활용
   url: /project/ai-mlp/
   parent: project
   weight: 35
 - name: 미래 계획
   url: /goals/
   identifier: goals
   weight: 40
 - name: 전체
   url: /goals/
   parent: goals
   weight: 41  
 - name: 로드맵
   url: /goals/roadmap/
   parent: goals
   weight: 42
 - name: 자격증
   url: /goals/certs/
   parent: goals
   weight: 43
 - name: 연락
   url: /contact/
   weight: 50
